Logic UI integration
mmalofeev/Meowchkin pull request #15
Opened 2024-04-20 23:32 UTC by pppppptttttt

2024-04-26 19:14 UTC, mmalofeev requested changes

2024-04-26 19:14 UTC, mmalofeev commented on include/game_session.hpp
> +    GameView &game_view;
please check the lifetimes and make sure there will be no use-after-free (since you store the reference)

2024-04-26 19:14 UTC, mmalofeev commented on src/scenes/raylib_game_view.cpp
> +#include <iostream>
please include headers from standard library after your headers
https://github.com/mmalofeev/Meowchkin/pull/9#discussion_r1564632934

2024-05-01 03:29 UTC, pppppptttttt commented on src/scenes/raylib_game_view.cpp
> +#include <iostream>
> please include headers from standard library after your headers [#9 (comment)](https://github.com/mmalofeev/Meowchkin/pull/9#discussion_r1564632934)

clang-format reorders them as he wants :c

2024-05-01 03:33 UTC, pppppptttttt commented on include/game_session.hpp
> +    GameView &game_view;
> please check the lifetimes and make sure there will be no use-after-free (since you store the reference)

there is none i hope, game_view is valid until his library unloads; and it happens in application dtor, even after game_session dtor(he declared earlier)

2024-05-05 19:19 UTC, pppppptttttt commented on include/game_session.hpp
> +    GameView &game_view;
upd: game_view will be shared_ptr

2024-05-05 19:19 UTC, merged