add model
mmalofeev/Meowchkin pull request #9
Opened 2024-03-22 13:53 UTC by mrprizmo

2024-04-14 11:40 UTC, mmalofeev requested changes

2024-04-14 11:40 UTC, mmalofeev commented on include/model_card.hpp
> +    const bool is_one_time{};
Advice for future: If you want to default initialize values, please use `const bool storable = false` instead of `const bool storable{}`. Personally I found first approach easier to read and debug

2024-04-14 11:40 UTC, mmalofeev commented on include/model_card.hpp
> +        CardInfo base,
I don't see any reason to do this way. Please explain in the comments why is it necessary. Just pass `CardInfo` arguments here and initialize abse class with this arguments 
```
SpellCardInfo(
    const std::string &image,
        std::size_t card_id,
        CardType type,
        bool openable,
        const std::vector<Command> &verification,
       ....) : CardInfo(image, id, type, ...)
```

2024-04-14 11:40 UTC, mmalofeev commented on include/model_card.hpp
> +        CardInfo base,
same comment as for `SpellCardInfo`

2024-04-14 11:40 UTC, mmalofeev commented on include/model_card_manager.hpp
> +#include "model_card.hpp"
FYI: there are 2 different approaches for includes: 
1) include EVERYTHING that you are using despite the fact that this include is already presented in your other files
(e.g. you are using string in your translation unit, so you include `<string>` even though it is already included in your other header file which is already included in this translation unit)
2) include only what is not presented in other includes

First approach seems weird to me (just personal preferences), so I would suggest stick to second approach. In this case you will need to firstly include headers with "higher-level logic" and append headers with low-level logic in the very end if it is necessary. 
So in your case you should fix your include order the following way:
```
#include "model_card.hpp"
#include <memory>
#include <string>
#include <vector>
```

2024-04-14 11:40 UTC, mmalofeev commented on include/model_card_manager.hpp
> +    static inline const std::string filename = "info.json";
we have a file which contains all of the string constants, please declare this filename there.

2024-04-14 11:40 UTC, mmalofeev commented on src/virtual_machine.cpp
> +                goto end_label;
holy shit

2024-04-15 22:42 UTC, mrprizmo commented on include/model_card.hpp
> +        CardInfo base,
I just don’t want to suffer when I add more inheritances of the CardInfo class or if I change CardInfo fields. besides I think in this way code looks more readable.

2024-04-17 14:06 UTC, mmalofeev approved these changes

2024-04-17 16:11 UTC, merged